apiVersion: v1
name: mlrun-ce
version: 0.6.4-rc14
description: MLRun Open Source Stack
home: https://iguazio.com
icon: https://www.iguazio.com/wp-content/uploads/2019/10/Iguazio-Logo.png
sources: []
maintainers:
  - name: MLRun
    email: mlrun@iguazio.com
    url: https://www.mlrun.org/
