apiVersion: v1
version: 0.0.21
name: mlrun-ce
description: MLRUn Open Source Stack
home: https://iguazio.com
icon: https://www.iguazio.com/wp-content/uploads/2019/10/Iguazio-Logo.png
sources: []
maintainers:
  - name: Adam Melnick
    email: adamm@iguazio.com
  - name: Eliyahu Noach
    email: eliyahun@iguazio.com
