{{- if .Values.pipelines.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: mlrun-pipelines-config
data:
  MLRUN_KFP_URL: http://ml-pipeline.{{.Release.Namespace}}.svc.cluster.local:8888
{{- end -}}
