{{- if index .Values.mlrun.modelMonitoring.provisionDB -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: mlrun-model-monitoring-db-config
data:
  MLRUN_MODEL_ENDPOINT_MONITORING__ENDPOINT_STORE_CONNECTION: {{ template "mlrun-ce.mlrun.modelMonitoring.DSN" .}}
{{- end }}
