{{- if index .Values.mlrun.modelMonitoring.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: mlrun-model-monitoring-db-config
data:
{{- if .Values.mlrun.modelMonitoring.dsn}}
  MLRUN_MODEL_ENDPOINT_MONITORING__ENDPOINT_STORE_CONNECTION: {{ .Values.mlrun.modelMonitoring.dsn }}
{{- else }}
  MLRUN_MODEL_ENDPOINT_MONITORING__ENDPOINT_STORE_CONNECTION: mysql+pymysql://root@mlrun-db:3306/monitoring
{{- end }}
{{- end -}}